package com.gr.account.service.dao.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.support.GeneratedKeyHolder;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class AbstractDaoImpl {

    @Autowired
    protected JdbcTemplate jdbcTemplate;
    public Number insertWithAutoGeneratedKey(final String sql, final String idColumnName, final Object... args) {
        GeneratedKeyHolder key = new GeneratedKeyHolder();
        PreparedStatementCreator preparedStatement = new PreparedStatementCreator() {
            public PreparedStatement createPreparedStatement(Connection con) throws SQLException {
                PreparedStatement ps = con.prepareStatement(sql, new String[]{idColumnName});

                for(int i = 0; i < args.length; ++i) {
                    ps.setObject(i + 1, args[i]);
                }

                return ps;
            }
        };
        this.jdbcTemplate.update(preparedStatement, key);
        return key.getKey();
    }
}
